name: Java CI

on:
  push:
    branches: 
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.11
      uses: actions/setup-java@v1
      with:
        java-version: 1.11
    - name: Build with Gradle
      run: ./gradlew build
    - name: Publish artifact
      run: ./gradlew publish
      env:
        gpr.user: karmann-dm
        gpr.key: ${{ secrets.GITHUB_TOKEN }}
